"""Поменял поле model со String на Text

Revision ID: 01c209d85603
Revises: e4e48dd91358
Create Date: 2025-03-29 17:50:06.056660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c209d85603'
down_revision: Union[str, None] = 'e4e48dd91358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disk_type_model', 'model',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='soundscan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disk_type_model', 'model',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='soundscan')
    # ### end Alembic commands ###
