"""Добавлено каскадное удаление

Revision ID: 70f5f3aedd73
Revises: 8e59825a64b1
Create Date: 2025-01-25 15:30:57.052370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f5f3aedd73'
down_revision: Union[str, None] = '8e59825a64b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blade_disk_scan_id_fkey', 'blade', schema='soundscan', type_='foreignkey')
    op.create_foreign_key(None, 'blade', 'disk_scan', ['disk_scan_id'], ['id'], source_schema='soundscan', referent_schema='soundscan', ondelete='CASCADE')
    op.drop_constraint('disk_scan_disk_type_id_fkey', 'disk_scan', schema='soundscan', type_='foreignkey')
    op.create_foreign_key(None, 'disk_scan', 'disk_type', ['disk_type_id'], ['id'], source_schema='soundscan', referent_schema='soundscan', ondelete='CASCADE')
    op.drop_constraint('disk_type_model_disk_type_id_fkey', 'disk_type_model', schema='soundscan', type_='foreignkey')
    op.create_foreign_key(None, 'disk_type_model', 'disk_type', ['disk_type_id'], ['id'], source_schema='soundscan', referent_schema='soundscan', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disk_type_model', schema='soundscan', type_='foreignkey')
    op.create_foreign_key('disk_type_model_disk_type_id_fkey', 'disk_type_model', 'disk_type', ['disk_type_id'], ['id'], source_schema='soundscan', referent_schema='soundscan')
    op.drop_constraint(None, 'disk_scan', schema='soundscan', type_='foreignkey')
    op.create_foreign_key('disk_scan_disk_type_id_fkey', 'disk_scan', 'disk_type', ['disk_type_id'], ['id'], source_schema='soundscan', referent_schema='soundscan')
    op.drop_constraint(None, 'blade', schema='soundscan', type_='foreignkey')
    op.create_foreign_key('blade_disk_scan_id_fkey', 'blade', 'disk_scan', ['disk_scan_id'], ['id'], source_schema='soundscan', referent_schema='soundscan')
    # ### end Alembic commands ###
