"""Update device config model

Revision ID: 7951af881f3c
Revises: cf4d9cd2e3ad
Create Date: 2024-09-27 10:12:30.628249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7951af881f3c'
down_revision: Union[str, None] = 'cf4d9cd2e3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_config', sa.Column('operating_port', sa.String(), nullable=True), schema='soundscan')
    op.add_column('device_config', sa.Column('SerialBaudRate', sa.Integer(), nullable=True), schema='soundscan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_config', 'SerialBaudRate', schema='soundscan')
    op.drop_column('device_config', 'operating_port', schema='soundscan')
    # ### end Alembic commands ###
