"""Изменение типа столбца scan в таблице Blade со String на LargeBinary

Revision ID: 7ae1b424ca60
Revises: 8d9f274a704f
Create Date: 2024-10-28 05:17:24.428788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae1b424ca60'
down_revision: Union[str, None] = '8d9f274a704f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blade', 'scan',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=False,
               schema='soundscan',
                postgresql_using='scan::bytea')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blade', 'scan',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='soundscan',
                postgresql_using='scan::text')
    # ### end Alembic commands ###
