"""initial migration

Revision ID: 831038e36e23
Revises: 
Create Date: 2024-09-26 10:55:26.694887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831038e36e23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_diameter', sa.Float(), nullable=True),
    sa.Column('base_motor_speed', sa.Float(), nullable=True),
    sa.Column('base_motor_accel', sa.Float(), nullable=True),
    sa.Column('base_motor_MaxSpeed', sa.Float(), nullable=True),
    sa.Column('head_motor_speed', sa.Float(), nullable=True),
    sa.Column('head_motor_accel', sa.Float(), nullable=True),
    sa.Column('head_motor_MaxSpeed', sa.Float(), nullable=True),
    sa.Column('head_motor_returning_speed', sa.Float(), nullable=True),
    sa.Column('head_motor_returning_accel', sa.Float(), nullable=True),
    sa.Column('head_working_pos', sa.Float(), nullable=True),
    sa.Column('tenzo_update_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='soundscan'
    )
    op.create_table('disk_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('blade_distance', sa.Integer(), nullable=False),
    sa.Column('blade_force', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='soundscan'
    )
    op.create_table('disk_scan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('disk_type_id', sa.Integer(), nullable=False),
    sa.Column('is_training', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disk_type_id'], ['soundscan.disk_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='soundscan'
    )
    op.create_table('disk_type_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disk_type_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disk_type_id'], ['soundscan.disk_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='soundscan'
    )
    op.create_table('blade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disk_scan_id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('scan', sa.String(), nullable=False),
    sa.Column('prediction', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disk_scan_id'], ['soundscan.disk_scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='soundscan'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blade', schema='soundscan')
    op.drop_table('disk_type_model', schema='soundscan')
    op.drop_table('disk_scan', schema='soundscan')
    op.drop_table('disk_type', schema='soundscan')
    op.drop_table('device_config', schema='soundscan')
    # ### end Alembic commands ###
