"""added new field is_current to DiskTypeModel

Revision ID: 93d6abf1cee6
Revises: 01c209d85603
Create Date: 2025-03-29 20:25:32.592913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d6abf1cee6'
down_revision: Union[str, None] = '01c209d85603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disk_type_model', sa.Column('is_current', sa.Boolean(), nullable=False, server_default=sa.false()), schema='soundscan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disk_type_model', 'is_current', schema='soundscan')
    # ### end Alembic commands ###
