"""поле предскахание теперь может быть None

Revision ID: e4e48dd91358
Revises: 70f5f3aedd73
Create Date: 2025-03-25 19:37:18.912737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e48dd91358'
down_revision: Union[str, None] = '70f5f3aedd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blade', 'prediction',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='soundscan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blade', 'prediction',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='soundscan')
    # ### end Alembic commands ###
